### PR TITLE
Optional user ID and time settings for jobber tasks

### LINKED ISSUE #18: User ID setting for jobber tasks
Hi @ondj,

can we add a config variable which defines the user id for jobber tasks (.jobber)?
I have a setup where all users must be authenticated using oidc so i had to delete the initial created admin user.

If this is ok for you, I will implement this and create a pull request.
When not, please let me know if there is another solution.

### PR DESCRIPTION
**Pull request by Benni0**
Added optional user ID and settings for Jobber tasks. User Id must be set when the initial created admin@admin.test user is deleted. Time settings provide more flexibility.

Fixes #18

### CODE REVIEW

**Comment by ondj** [comment]
Can you please also add `JOBBER_USER_ID` variable to int variables check?

https://github.com/NUKIB/misp/blob/3eb927791c30ef60653a7f53b0d205e92fd067d6/bin/misp_create_configs.py#L82

**Comment by Benni0** [comment]
I've added JOBBER_USER_ID to int variables check.
Sorry I've missed that.

**Comment by Benni0** [comment]
I think there is currently a problem in the build task which is not dependent on my changes.
grafik

**Comment by ondj** [comment]
> I think there is currently a problem in the build task which is not dependent on my changes.

Yes, it looks like that container-scan has problem: https://github.com/Azure/container-scan/issues/122. I will temporary remove that scan.

**Pull request merged**
